import React from 'react';
import Head from 'next/head'
import Script from 'next/script'

import { FaAngleUp, } from 'react-icons/fa';

import Header from "components/header/Header"
import Footer from 'components/footer/Footer';

import ParticleImg from 'components/ParticleImg';
import SlideImgItem from 'components/SlideImgItem';
import SkillViewChart from 'components/SkillViewChart';
import SkillsView from 'components/SkillsView';

type Props = {  
}

type ContactState = {
  yourname:string,
  email:string,
  subject:string,
  message:string,
}
class Home extends React.Component<Props, ContactState> { 

  form = React.createRef<HTMLFormElement>();
  
  constructor(props:Props) {
    super(props)
  }
  state: ContactState = {yourname:'', email:'', subject:'', message:''};  
  
  handleChange = (event: { target: { name: string; value: string; }; }) => {
    let inputname:string = event.target.name
    let inputvalue:string = event.target.value;
    if (inputname==='yourname')  this.setState({yourname:inputvalue})
    if (inputname==='email')  this.setState({email:inputvalue})
    if (inputname==='subject')  this.setState({subject:inputvalue})
    if (inputname==='message')  this.setState({message:inputvalue})
  }  
  sendEmail = () => {
    console.log("submit");    
    console.log(this.state.yourname);
    window.open("mailto:darkrut22@gmail.com?subject=" + this.state.subject + "&" + this.state.message + "\n" + this.state.yourname);
  };

  render(){
    return (
      <>
        <Head>
          <title>My Web</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        
        <main className="glory-main-wraper relative" data-spy="scroll" data-target=".navbar" data-offset="70">
          {/* ----------here-------  */}
          <div id='here' className='w-full h-[100vh] relative'>
            <iframe src="/assets/pages/threejs-particle-rotate/index.html" className='absolute top-0 left-0 w-full h-[100vh]' style={{zIndex:'-1'}}/>
            <Header />
            <div className='flex justify-center items-end h-[100vh] absolute top-0 left-0 w-full'>
              <div className='content'>
                <div className='content-col'>
                  <div>
                    <img src="assets/img/text.png"/>                  
                    <div className='md:w-full flex justify-center'>
                      <button className="btn btn-here bg-white hover:bg-red border-2 border-white font-medium hover:text-white text-red px-6 py-3" type="submit" id="sendMessageButton"
                        style={{transition: "ease-out 0.3s",boxShadow: "rgba(0, 0, 0, 0.7) 3px 6px 5px"}}>Contact Me</button>
                    </div>
                  </div>
                </div>                
                <div className='content-col'>
                  <div className='right-img'>
                    <img src="assets/img/man1.png" className=''/>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* ----------about-------  */}
          <div id='about' className="glory-about-me bg-white ">            
            <div className='md:flex md:items-center'>
              <div className='about-me-particle-image w-full md:w-2/6 p-8  flex justify-center items-center'>                
                <ParticleImg/>                
              </div>
              <div className='about-me-description w-full md:w-4/6 h-full p-8 flex items-center justify-center'>
                <div>
                  <div className='text-xl md:text-40 text-center text-gray-700 font-bold mb-8'>Creative, Passionate and Efficient Developer</div>
                  <div className='text-base md:text-lg font-normal text-gray-500 '>
                    Creative, Passionate and Efficient Sofrware developer with over 10 years of experience in web, mobile and desktop applications design, development and maintenance. Possesses diverse experience of creating multiple highly scalable applications using different tech stacks. Have worked in all phases of the project life cycle, using a wide variety of tools and frameworks. Implemented 3D Web, Virtual Reality with Three.js and WebGL.<br/>
                    Leaded successful transition from LAMP Stack to MEAN Stack to reduce development time and improve system performance.<br/>
                    Have strong and advanced algorithim logic.<br/>
                    And have hands-on experience in web hosting & maintenance, Browser Automation and testing, Web Scraping & Crawling.<br/> 
                    I prefer to build trust and a long-term relationships.
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* ----------resume-------  */}
          <div id='resume' className="glory-resume w-full relative">
            <div className='w-full h-full flex items-center justify-center text-gray-500' > 
              <div>
                <div className='grid grid-cols-1 md:grid-cols-3 w-full h-full md:h-auto '>
                  <div className='resume-description h-full flex items-center justify-center'>
                    <div className='pt-8 md:pb-8 pl-8 pr-8 md:pr-0'>
                      <div className='text-lg font-semibold mb-3'>Education</div>
                      <div className='text-lg font-semibold mb-3 text-gray-700'>
                        <b className='text-red'>Bachelor of Computer Science</b><br/>Kuban State Technological University
                      </div>
                      <div className='text-base font-normal'>
                        Kuban State Technological University, also referred to as the Kuban
                        State University of Technology, is a Russian public technical university
                        located in Krasnodar, one of the first higher educational institutions
                        established in the southern region of Russia.<br/>
                        <b>Relevant Coursework</b> : Operating Systems Architecture, Linux/Unix
                        Programming, Usability in Website and Software Design, C++
                        Programming, Web Page Development, Relational Database Design &
                        SQL, Data Engineering, Advanced Software Programming
                      </div>
                    </div>
                  </div>       
                  <div className='resume-description h-full flex items-center md:items-start justify-center'>
                    <div className='pt-8 md:pb-8 pl-8 pr-8 md:pr-0'>
                      <div className='text-lg font-semibold text-gray-700 mb-3'>
                        Experience | Frontend Developer <br/><b className='text-red'>ASPIRITY</b> From 2014 to 2017
                      </div>
                      <div className='text-base font-normal'>
                        <ul>
                          <li>✔ Implemented responsive web pages and mobile UI from concept through deployment</li>
                          <li>✔ Implemented efficient and reusable front-end modules that drive complex web applications</li>
                          <li>✔ Implemented 3D Scene, 3D Animation, Augmented reality(AR) and Virtual Reality(VR) with Three.js and Babylon.js</li>
                          <li>✔ Implemented new responsive, mobile-first approach which increased mobile traffic by 10%.</li>
                        </ul>
                      </div>
                    </div>
                  </div>      
                  <div className='resume-description h-full flex items-center md:items-start justify-center'>
                    <div className='p-8'>
                      <div className='text-lg font-semibold text-gray-700 mb-3'>
                        Experience | Full Stack Developer <br/><b className='text-red'>Artezio</b> From 2017 to 2020
                      </div>
                      <div className='text-base font-normal'>
                        <ul>
                          <li>✔ Improved the performance of whole system with efficiency memory usage, multithreading, distributed computing, and other various ideas.</li>
                          <li>✔ Developed app integration with RESTful and other APIs for Google Maps, social media logins, payment processors, blockchain wallet, and other services.</li>
                          <li>✔ Implemented various bots, browser automation, and automation scripts.</li>
                        </ul>
                      </div>
                    </div>
                  </div>   
                </div>
              </div>    
            </div>
          </div>

          {/* ----------portfolio-------  */}
          <div id='portfolio' className="glory-portfolio bg-transparent flex justify-center items-center p-8 relative">
            <div className='w-full h-full z-10'>              
              <div className='title w-full text-center font-bold text-32 md:text-45 text-white mb-8'>
                My Excellent Portfolio
              </div>
              <div className='grid grid-cols-1 md:grid-cols-3 relative gap-8'>
                <SlideImgItem imgURL={"assets/img/portfolio/BlueJestic.png"} imgLink={"https://bluejestic.com/"} skillContent={"React + React Hook + Next.js + Node.js + Chart.js + TailwindCSS + SCSS + GraphQL"} />
                <SlideImgItem imgURL={"assets/img/portfolio/campoallecomete.png"} imgLink={"http://www.campoallecomete.it"} skillContent={"Three.js + WebGL"} />
                <SlideImgItem imgURL={"assets/img/portfolio/alethea.png"} imgLink={"https://alethea.ai/"} skillContent={"React + Node.js + WebGL + Video.js + BlockChain + NFT"} />
                <SlideImgItem imgURL={"assets/img/portfolio/exante.png"} imgLink={"https://exante.eu"} skillContent={"Backbone.js + particle.js + GoogleAPI + Python + Django"} />
                <SlideImgItem imgURL={"assets/img/portfolio/koenigandreas.png"} imgLink={"https://koenigandreas.com"} skillContent={"BootStrap4 + particle.js + PHP"} />
                <SlideImgItem imgURL={"assets/img/portfolio/lonelyplanet.png"} imgLink={"https://www.lonelyplanet.com"} skillContent={"React + Next.js + Node.js"} />
                <SlideImgItem imgURL={"assets/img/portfolio/ultranote.png"} imgLink={"https://cloud.ultranote.org"} skillContent={"React + Chart.js + BlockChain + UltraNote"} />
                <SlideImgItem imgURL={"assets/img/portfolio/bluestarcoffeeroasters.png"} imgLink={"https://bluestarcoffeeroasters.com/"} skillContent={"React + tailwindCSS + Shopify"} />
                <SlideImgItem imgURL={"assets/img/portfolio/lusion.png"} imgLink={"https://lusion.co/"} skillContent={"Three.js + WebGL"} />
                <SlideImgItem imgURL={"assets/img/portfolio/dnb.png"} imgLink={"https://dnb.ru/"} skillContent={"BootStrap + Python/Django"} />
                <SlideImgItem imgURL={"assets/img/portfolio/cools.png"} imgLink={"https://cools.com"} skillContent={"PHP/Laravel"} />
              </div>
            </div>
            <iframe src='/assets/pages/tsparticle/index.html' className='absolute left-0 top-0 w-full h-full z-0'/>
          </div>

          {/* ----------skill-------  */}
          <div id='skill' className="glory-skill p-8">
            <SkillViewChart/>
            <SkillsView/>
          </div>

          {/* ----------contact-------  */}
          <div id='contact' className="glory-contact" style={{backgroundColor:'#ff0000'}}>            
            <div className='md:flex items-center'>
              <div className='hidden md:block w-1/6'></div>
              <div className='hidden md:block w-2/6 justify-center items-center p-8 h-[350px]'>
                {/* <img src='assets/img/contact.png' className='w-full h-full p-8'/> */}
                <iframe src='/mailbox' className='w-full h-full '/>
              </div>
              <div className='h-full w-full md:w-2/6 text-base font-medium text-white p-8 flex items-center justify-center'>
                  <div className="contact-form w-full h-full">
                    <div id="success"></div>
                    <form name="sentMessage w-full h-full" id="contactForm" ref={this.form} >
                        <div className="control-group">
                          <input type="text" className="form-control" name="yourname" id="name" placeholder="Your Name" data-validation-required-message="Please enter your name"  onChange={this.handleChange.bind(this)}/>
                          <p className="help-block"></p>
                        </div>
                        <div className="control-group">
                          <input type="text" className="form-control" name="subject" id="subject" placeholder="Subject" data-validation-required-message="Please enter a subject"  onChange={this.handleChange.bind(this)}/>
                          <p className="help-block"></p>
                        </div>
                        <div className="control-group">
                          <textarea className="form-control" name="message" id="message" placeholder="Message" data-validation-required-message="Please enter your message" rows={3} onChange={this.handleChange.bind(this)}></textarea>
                          <p className="help-block"></p>
                        </div>
                        <div className='mt-8 w-full flex justify-center md:justify-start'>
                          <button className="btn w-auto bg-white hover:bg-red border-2 border-white font-medium hover:text-white text-red px-6 py-2" type="button" id="sendMessageButton" onClick={()=>this.sendEmail()}
                            style={{transition: "ease-out 0.3s"}} >Send Message</button>
                        </div>
                    </form>
                  </div>
              </div>
              <div className='hidden md:block w-1/6'></div>
            </div>
          </div>

          {/* -- Back to top button -- */}
          <a href="#" className="btn back-to-top" ><FaAngleUp /></a>
          <Footer/>
        </main>
        {/* <Script src="assets/js/jquery-3.4.1.min.js"/> */}
        <Script src="https://code.jquery.com/jquery-3.4.1.min.js"/>        
        <Script src="assets/lib/easing/easing.js"/>
        <Script src="assets/js/main.js"/>
      </>
    );
  }
}

export default Home
